//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStockTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockHistoricalPrice
    {
        public string StkCode { get; set; }
        public System.DateTime Date { get; set; }
        public double OpenPrice { get; set; }
        public double HighPrice { get; set; }
        public double LowPrice { get; set; }
        public double ClosePrice { get; set; }
        public double AdjustedClosePrice { get; set; }
        public double Volume { get; set; }
    
        public virtual ListedStock ListedStock { get; set; }

        public static implicit operator List<object>(StockHistoricalPrice v)
        {
            throw new NotImplementedException();
        }
    }
}
