//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStockTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockHistoricalPrice
    {
        public StockHistoricalPrice()
        {
             
        }
        public StockHistoricalPrice(
            string symbol,
            DateTime date,
            decimal open,
            decimal high,
            decimal low,
            decimal close,
            decimal volume)
        {
            StkCode = symbol;
            OpenPrice = open;
            HighPrice = high;
            LowPrice = low;
            ClosePrice = close;
            Date = date;
            Volume = volume;
        }

        public StockHistoricalPrice(
            string symbol,
            DateTimeOffset dateTime,
            decimal open,
            decimal high,
            decimal low,
            decimal close,
            decimal volume)
        {
            StkCode = symbol;
            Date = dateTime.DateTime;
            OpenPrice = open;
            HighPrice = high;
            LowPrice = low;
            ClosePrice = close;
            Volume = volume;
        }

        public string StkCode { get; set; }
        public System.DateTime Date { get; set; }
        public decimal OpenPrice { get; set; }
        public decimal HighPrice { get; set; }
        public decimal LowPrice { get; set; }
        public decimal ClosePrice { get; set; }
        public decimal Volume { get; set; }
    
        public virtual ListedStock ListedStock { get; set; }
    }
}
