//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoStockTransaction
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockHistoricalPrice
    {
        public StockHistoricalPrice()
        {
        }
        public StockHistoricalPrice(string stkcode,DateTime dateTime,decimal openPrice,decimal highPrice,decimal lowPrice,decimal closePrice, decimal volume)
        {
            this.StkCode = stkcode;
            this.Date = dateTime;
            this.OpenPrice = openPrice;
            this.HighPrice = highPrice;
            this.LowPrice = lowPrice;
            this.ClosePrice = closePrice;
            this.Volume = volume;
        }
        public string StkCode { get; set; }
        public DateTime Date { get; set; }
        public decimal OpenPrice { get; set; }
        public decimal HighPrice { get; set; }
        public decimal LowPrice { get; set; }
        public decimal ClosePrice { get; set; }
        public decimal Volume { get; set; }
    
        public virtual ListedStock ListedStock { get; set; }
    }
}
